//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversiteOtomasyon.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSONTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LESSONTb()
        {
            this.NOTESTb = new HashSet<NOTESTb>();
        }
    
        public int ID { get; set; }
        public string LESSONNAME { get; set; }
        public string CODE { get; set; }
        public string CREDIT { get; set; }
        public int EPIDOSEID { get; set; }
    
        public virtual EPIDOSE EPIDOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTESTb> NOTESTb { get; set; }
    }
}
