//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversiteOtomasyon.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGESS
    {
        public int ID { get; set; }
        public int SENDERID { get; set; }
        public int ANCHOVIESID { get; set; }
        public string MESSAGECONTENT { get; set; }
        public System.DateTime MESSAGESENDERDATE { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
