//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversiteOtomasyon.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTESTb
    {
        public int ID { get; set; }
        public int NOTADDEDID { get; set; }
        public int LESSONID { get; set; }
        public int UserDetailsId { get; set; }
        public string NOTVISA1 { get; set; }
        public string NOTVISA2 { get; set; }
        public string NOTFINAL { get; set; }
        public string NOTCOMPLETE { get; set; }
    
        public virtual LESSONTb LESSONTb { get; set; }
        public virtual UserDetails UserDetails { get; set; }
    }
}
