//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversiteOtomasyon.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UniversiteOtomasyonEntities : DbContext
    {
        public UniversiteOtomasyonEntities()
            : base("name=UniversiteOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANNOUNCEMENTS> ANNOUNCEMENTS { get; set; }
        public virtual DbSet<EPIDOSE> EPIDOSE { get; set; }
        public virtual DbSet<FACULTY> FACULTY { get; set; }
        public virtual DbSet<LESSONTb> LESSONTb { get; set; }
        public virtual DbSet<MESSAGESS> MESSAGESS { get; set; }
        public virtual DbSet<NOTESTb> NOTESTb { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    
        public virtual ObjectResult<getStudentList_Result> getStudentList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getStudentList_Result>("getStudentList");
        }
    
        public virtual int noteAddProcedure(Nullable<int> nOTADDEDID, Nullable<int> lESSONID, Nullable<int> userDetailsId, string nOTVISA1, string nOTVISA2, string nOTFINAL, string nOTCOMPLETE)
        {
            var nOTADDEDIDParameter = nOTADDEDID.HasValue ?
                new ObjectParameter("NOTADDEDID", nOTADDEDID) :
                new ObjectParameter("NOTADDEDID", typeof(int));
    
            var lESSONIDParameter = lESSONID.HasValue ?
                new ObjectParameter("LESSONID", lESSONID) :
                new ObjectParameter("LESSONID", typeof(int));
    
            var userDetailsIdParameter = userDetailsId.HasValue ?
                new ObjectParameter("UserDetailsId", userDetailsId) :
                new ObjectParameter("UserDetailsId", typeof(int));
    
            var nOTVISA1Parameter = nOTVISA1 != null ?
                new ObjectParameter("NOTVISA1", nOTVISA1) :
                new ObjectParameter("NOTVISA1", typeof(string));
    
            var nOTVISA2Parameter = nOTVISA2 != null ?
                new ObjectParameter("NOTVISA2", nOTVISA2) :
                new ObjectParameter("NOTVISA2", typeof(string));
    
            var nOTFINALParameter = nOTFINAL != null ?
                new ObjectParameter("NOTFINAL", nOTFINAL) :
                new ObjectParameter("NOTFINAL", typeof(string));
    
            var nOTCOMPLETEParameter = nOTCOMPLETE != null ?
                new ObjectParameter("NOTCOMPLETE", nOTCOMPLETE) :
                new ObjectParameter("NOTCOMPLETE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("noteAddProcedure", nOTADDEDIDParameter, lESSONIDParameter, userDetailsIdParameter, nOTVISA1Parameter, nOTVISA2Parameter, nOTFINALParameter, nOTCOMPLETEParameter);
        }
    }
}
