//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversiteOtomasyon.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetails()
        {
            this.NOTESTb = new HashSet<NOTESTb>();
        }
    
        public int ID { get; set; }
        public string NAMESURNAME { get; set; }
        public Nullable<long> NUMBER { get; set; }
        public string TCNUMBER { get; set; }
        public bool GENDER { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public string ADDRES { get; set; }
        public string TELNUMBER { get; set; }
        public int FACULTY { get; set; }
        public int EPIDOSE { get; set; }
        public Nullable<int> USERCLASS { get; set; }
        public string IMAGES { get; set; }
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual EPIDOSE EPIDOSE1 { get; set; }
        public virtual FACULTY FACULTY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTESTb> NOTESTb { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
